name: Build johnd-lambda

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    permissions:
      id-token: write
      contents: read
    name: johnd-lambda build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Coursier cache
        uses: coursier/cache-action@v6.3

      - name: install scala-cli
        uses: VirtusLab/scala-cli-setup@main

      - name: Test project
        run: scala-cli test scala

      - name: Compile and package project
        run: scala-cli --power package scala -o lambda.jar --assembly --preamble=false --force

      - name: Generate CFN templates from GuCDK
        run: bash ./generate-cfn.sh

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: johnd-lambda
          configPath: ./riff-raff.yaml
          contentDirectories: |
            cfn:
              - ./cdk/cdk.out/JohndLambda-euwest-1-CODE.template.json
            johnd-lambda:
              - ./lambda.jar