name: Build johnd-lambda

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    permissions:
      id-token: write
      contents: read
    name: johnd-lambda build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Coursier cache
        uses: coursier/cache-action@v6.3

      - name: install scala-cli
        uses: VirtusLab/scala-cli-setup@main

      - name: Test project
        run: scala-cli test scala

      - name: Compile and package project
        run: scala-cli --power package scala -o johnd-lambda-${{ github.run_number }}.jar --assembly --preamble=false --force

      - name: Generate CFN templates from GuCDK
        run: bash ./generate-cfn.sh

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: johnd-lambda
          config: |
            stacks: [playground]
            regions: [eu-west-1]

            allowedStages:
              - CODE

            deployments:
              johnd-lambda-cfn:
                type: cloud-formation
                parameters:
                  templateStagePaths:
                    CODE: JohndLambda-euwest-1-CODE.template.json
                  cloudFormationStackName: johnd-lambda
              johnd-lambda:
                type: aws-lambda
                parameters:
                  bucketSsmLookup: true
                  functionNames: [johnd-lambda-]
                  fileName: johnd-lambda-${{ github.run_number }}.jar
                  prefixStack: false
                dependencies: [johnd-lambda-cfn]

          contentDirectories: |
            johnd-lambda-cfn:
              - ./cdk/cdk.out/JohndLambda-euwest-1-CODE.template.json
            johnd-lambda:
              - ./johnd-lambda-${{ github.run_number }}.jar